apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api
  namespace: todo-api
  labels:
    app: todo-api
spec:
  replicas: 5
  selector:
    matchLabels:
      app: todo-api
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      containers:
        - name: todo-api
          image: docker.io/library/nginx:alpine
          ports:
            - containerPort: 80
              name: http

          # Variables d'environnement inutiles pour nginx mais conservées pour respecter la structure
          env:
            - name: PORT
              value: "3000"
            - name: NODE_ENV
              value: "production"

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
