apiVersion: v1
kind: Service
metadata:
  name: todo-api
  namespace: todo-api
  labels:
    app: todo-api
spec:
  type: ClusterIP
  selector:
    app: todo-api
  ports:
    - name: http
      port: 80         # Port accessible dans le cluster
      targetPort: http # Fait référence au port nommé dans le container
      protocol: TCP
